### ISSUE TITLE
Would you like to write/add Readme for this in step by step manner ?

### ISSUE THREAD

**Issue by ghost** [italomaia/vuejs-python#2]
Would you like to write/add Readme for this in step by step manner ? If you do, its  really appreciable

**Comment by italomaia** [comment]
@sanjay555  seems like a good idea. Gimme a few days.

**Comment by italomaia** [comment]
What about now? https://github.com/italomaia/vuejs-python/blob/master/README.rst

**Comment by ghost** [comment]
Cool
